### ISSUE TITLE
column-based  GEMV

### ISSUE THREAD

**Issue by MikeChenfu** [wangsiping97/FastGEMV#1]
Hello, Thanks for the gemv code. And I saw the matrix-A is row-based matrix. Do you have any idea about column-based matrix? It is like vector * matrix. Thanks.

**Comment by wangsiping97** [comment]
Assessing column-based matrix with GPU can be slower than row-based due to the lack of cache locality. The simplest way I can think of is to first transpose the matrix (or store the matrix in a transposed way) and then it should be the same as GEMV.

**Comment by MikeChenfu** [comment]
Thanks, that makes sense to me. :)

**Comment by TylunasLi** [comment]
[yzhaiustc/Optimizing-SGEMV-on-NVIDIA-GPUs](https://github.com/yzhaiustc/Optimizing-SGEMV-on-NVIDIA-GPUs) is a column based GEMV, but only fp32 are supported.

**Comment by quaternior** [comment]
Hello, I'm currently looking for an efficient GEMV kernel(especially with column-major form), and I'm curious about the reason why the column-major matrix is slower because of the cache locality? I read the cutlass gemv issue and they said that column-major matrix is more efficient because of the memory coalescing. 

Thanks!
